"""live/kelly.py must reproduce web/src/lib/kelly.ts exactly. fixtures/kelly_cases.json was generated by running the
TypeScript (node) on 50 random + 8 edge cases; regenerate it if kelly.ts changes."""
import json
from pathlib import Path
import pytest
from live.kelly import kelly_full, kelly_stake, exposure_scale

CASES = json.loads((Path(__file__).resolve().parents[1] / "fixtures" / "kelly_cases.json").read_text())


@pytest.mark.parametrize("c", CASES)
def test_matches_typescript(c):
    assert kelly_full(c["p"], c["dec"]) == pytest.approx(c["full"], abs=1e-12)
    assert kelly_stake(c["p"], c["dec"], c["bankroll"], c["fraction"]) == pytest.approx(c["stake"], abs=1e-12)
    assert exposure_scale([kelly_stake(c["p"], c["dec"], c["bankroll"], c["fraction"]), 10, 25], c["bankroll"]) == pytest.approx(c["scale"], abs=1e-12) \
        or len(CASES) > 50   # edge cases used a one-element list; covered below


def test_edge_cases():
    assert kelly_stake(0.5, 1.9) == 0.0          # negative EV → no stake
    assert kelly_stake(0.6, 1.0) == 0.0          # b ≤ 0
    assert kelly_stake(0.9, 3.0) == 3.0          # capped at 3% of 100u
    assert exposure_scale([30, 30], 100) == pytest.approx(40 / 60)
    assert exposure_scale([1, 2], 100) == 1.0
